# This file was generated by GoReleaser. DO NOT EDIT.
cask "korean-tui" do
  version "1.0.6"

  on_macos do
    on_intel do
      sha256 "f3e2e25647763bab443d8341c03a81e4c5ba856b348240beb4a22982e6588355"
      url "https://github.com/arthurblanchet59/korean-learning-go/releases/download/v#{version}/korean-tui_#{version}_darwin_amd64"
      binary "korean-tui_1.0.6_darwin_amd64", target: "korean-tui"
    end
    on_arm do
      sha256 "607535380c501f9225d8009384b9b06b55f291ad0c937f772e221f5623f470c4"
      url "https://github.com/arthurblanchet59/korean-learning-go/releases/download/v#{version}/korean-tui_#{version}_darwin_arm64"
      binary "korean-tui_1.0.6_darwin_arm64", target: "korean-tui"
    end
  end

  on_linux do
    on_intel do
      sha256 "b4c9cb2096905e8f70580d4596e3679b6b9bec8fd038cfdf657e4fe1846ffe5e"
      url "https://github.com/arthurblanchet59/korean-learning-go/releases/download/v#{version}/korean-tui_#{version}_linux_amd64"
      binary "korean-tui_1.0.6_linux_amd64", target: "korean-tui"
    end
    on_arm do
      sha256 "1e1db3273b692bfedcd4e59154d647ffbd86574f85091d566b86020787bd3c74"
      url "https://github.com/arthurblanchet59/korean-learning-go/releases/download/v#{version}/korean-tui_#{version}_linux_arm64"
      binary "korean-tui_1.0.6_linux_arm64", target: "korean-tui"
    end
  end

  name "korean-tui"
  desc "Client terminal pour reviser le coreen (korean-learning-go)"
  homepage "https://github.com/arthurblanchet59/korean-learning-go"

  livecheck do
    skip "Auto-generated on release."
  end

  # No zap stanza required

end
