# This file was generated by GoReleaser. DO NOT EDIT.
cask "korean-tui" do
  version "1.0.7"

  on_macos do
    on_intel do
      sha256 "60524c5fc30333c6eb80325422a5a8900dfe2f69b859e49439d1cf4f2b025416"
      url "https://github.com/arthurblanchet59/korean-learning-go/releases/download/v#{version}/korean-tui_#{version}_darwin_amd64"
      binary "korean-tui_1.0.7_darwin_amd64", target: "korean-tui"
    end
    on_arm do
      sha256 "21c20742b8ef9f50906c966226ef50ac634cd8bf8f7ffc76033a1917eb54febb"
      url "https://github.com/arthurblanchet59/korean-learning-go/releases/download/v#{version}/korean-tui_#{version}_darwin_arm64"
      binary "korean-tui_1.0.7_darwin_arm64", target: "korean-tui"
    end
  end

  on_linux do
    on_intel do
      sha256 "94967b833be1e4d3e171a7697ed4be1ba537e7370aa6b81bb88f090f1b45cb4d"
      url "https://github.com/arthurblanchet59/korean-learning-go/releases/download/v#{version}/korean-tui_#{version}_linux_amd64"
      binary "korean-tui_1.0.7_linux_amd64", target: "korean-tui"
    end
    on_arm do
      sha256 "f2479aa1dac6d4ce50a6908a65824d321a2563e2e44846ee6c37b5ed3fe3c09e"
      url "https://github.com/arthurblanchet59/korean-learning-go/releases/download/v#{version}/korean-tui_#{version}_linux_arm64"
      binary "korean-tui_1.0.7_linux_arm64", target: "korean-tui"
    end
  end

  name "korean-tui"
  desc "Client terminal pour reviser le coreen (korean-learning-go)"
  homepage "https://github.com/arthurblanchet59/korean-learning-go"

  livecheck do
    skip "Auto-generated on release."
  end

  # No zap stanza required

end
