# This file was generated by GoReleaser. DO NOT EDIT.
cask "korean-tui" do
  version "1.0.9"

  on_macos do
    on_intel do
      sha256 "32d36d9d89e98fc4cf8d217c4f3fa709cc66de8e80758ff3368dbe4b36379958"
      url "https://github.com/arthurblanchet59/korean-learning-go/releases/download/v#{version}/korean-tui_#{version}_darwin_amd64"
      binary "korean-tui_1.0.9_darwin_amd64", target: "korean-tui"
    end
    on_arm do
      sha256 "44285080ffaedfc71c2e4ce75cdbf363efdbeedd213eafdfb4a38fa771808b05"
      url "https://github.com/arthurblanchet59/korean-learning-go/releases/download/v#{version}/korean-tui_#{version}_darwin_arm64"
      binary "korean-tui_1.0.9_darwin_arm64", target: "korean-tui"
    end
  end

  on_linux do
    on_intel do
      sha256 "6080a0a50f2cd61676e4633ef3d9827bde7c9965f6214560974fb6786ce26974"
      url "https://github.com/arthurblanchet59/korean-learning-go/releases/download/v#{version}/korean-tui_#{version}_linux_amd64"
      binary "korean-tui_1.0.9_linux_amd64", target: "korean-tui"
    end
    on_arm do
      sha256 "6ac043581c0d22379d36686fd211ffeaa416c372654abb905d00e15c5fa73149"
      url "https://github.com/arthurblanchet59/korean-learning-go/releases/download/v#{version}/korean-tui_#{version}_linux_arm64"
      binary "korean-tui_1.0.9_linux_arm64", target: "korean-tui"
    end
  end

  name "korean-tui"
  desc "Client terminal pour reviser le coreen (korean-learning-go)"
  homepage "https://github.com/arthurblanchet59/korean-learning-go"

  livecheck do
    skip "Auto-generated on release."
  end

  # No zap stanza required

end
